# pipeline image
image: docker:latest

variables:
  REGISTRY_URL: "harbor.devsecops.yukanyan.us.kg"
  REGISTRY_PROJECT: "devsecops-demo-app"

# sidecar
services:
  - name: docker:dind
    # http
    command:
      [
        '--insecure-registry=harbor.devsecops.yukanyan.us.kg',
      ]

stages:
  - build

# install git & ssh before job run
before_script:
  - apk add --no-cache git
  - "which ssh-agent || ( apk update -y && apk add openssh-client git -y )"
  - eval $(ssh-agent -s)
  - echo "$HARBOR_PASSWORD" | docker login $REGISTRY_URL -u $HARBOR_USERNAME --password-stdin

build:
  stage: build
  script:
    - |
      for dir in */
      do
        dir=${dir%*/}
        if git diff --quiet HEAD^ HEAD -- ./$dir
        then
          echo "$dir: false" >> changed_dirs.txt
        else
          echo "$dir: true" >> changed_dirs.txt
        fi
      done
      cat changed_dirs.txt
    - |
      while IFS= read -r line
      do
        dir=$(echo $line | cut -d ':' -f 1)
        changed=$(echo $line | cut -d ' ' -f 2)
        if [ "$changed" == "true" ] && [ -f "./$dir/Dockerfile" ]
        then
          docker build -t $REGISTRY_URL/$REGISTRY_PROJECT/$dir:${CI_COMMIT_SHA} ./$dir
          docker push $REGISTRY_URL/$REGISTRY_PROJECT/$dir:${CI_COMMIT_SHA}
        fi
      done < changed_dirs.txt