apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAkUzagOqrUMGgxzj+uhqHi8YRen1omXKazl5cRmc6JkK8uu/uyAO+RLWExgODgKB1u8YD6wgS2/jkFn87tEOFuaxqBvZHhf0dtgZVygpg0GdGq7FNDoEr3FVkX68CLmqVlpI1100m+hjYNyhvvOSqHPlQUz/eBNAglOr8hAkX++/C+knw2ZYKvozkM4jaez5HaUf5NJd+fzHYj1HwOu3OOWp532qSKCBCTvforC7kNOH9Gx00OrUoDX5kJGtEgnU7Tik0adDSVtI2iyU9sdXjmGwQQU7FN3JMHQjrc3UZpXrl0mHz2hVA++UDjyZnHA/NKbfJHOLolpmRkz/s6WR4eZy9NEG2RvDGTszjFu+zWmVYzRaIv8Sq+cYriloxZjG2GUdYULsZYxANC03xI2dz73jkbkOc/0b5IfrGTh5DZjWj2cSJP6n7FKDpkUBaB8Fttf3cuVbPkfFmwLPCUHJfgGLkM1ObEaMMiTLwuxP1ONTMVA3lOP0cixoYi6RFptejjYcHH4QWbPjDyTVEhEssm2zmH2xEYm/iR54JNZH6SV/u3CUZD8q4BU9giSDIBW/YVHv/Yazv5GQsIuUyJrA0XI1zFTU/an6ogiZkTpM1Uu/PA9IH+d1kgM31Z/e0OodEJ1DX29CyVuq8caAwTFWB5Rd5f9zS+xlR2HXl96BwJ4C5ux+fGoVml4Y8pHUKYzDNZBX+GvRth9qkuvqbDC3JaENdW2l/LiDmzXEP8L/PLZvcDBRjQz1Vq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

