apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCTCgnnr1FS2mIf3CddKEbHmxWg1xat3t2QZ8GSac7T+X6Ogv7FSLdmBPqGM6dLYv3eW1P0+WjE+6a1RHx59+2Ydo2XeFG8SFe9LKh6KrClpxgYwdBf8dc4kpuvw158GZqNwVqEfNmXk0xt9vzjDsedjJDIAZ1KXCNIFyRaLjkISGeaGk0XxHuSrlKQMIx0BCLnM6t/F61QX3+2LxpbRscT8ko+GpTO26u6iHSz1XYZnJetEfDHK4obpgDZt27X03J6WBCz1wIsaZcjYt1Fa56UJ7pvuOZp8sZUsnWpe6QnaPkIGf0vClUKXfDNpRQm4C0LqdxVv9hkamGvWEPeB0GA5MNw9UPxzJNpPVwPe/oaWQu+qM1lFrY3+lkMprVCnOUc+fYSZ8XH2orUwrhawgqQJVlMMAKUQhmXN1MApq83UdeA1i/ntY+sPtubIgSxu16ZO44sG1KGFnAxSLZMRZtn0Nl4Qri8dk7TfmLNJW6MwEKDuS8y9uE2yWbPe8UkqiFMhOaN/WRrFZve7B0vWhlHDg42Hlb6eNe/b9TmngdO+AmPN7qOdghd9vVC5GKvEARkcl6iuHAH3cVSiVS91/6EKBoehDlY6Xb2oDvFpohMVoRzjQrJ6mVzaOiJAcMSJDh6BCmy9vD2N6XRR7V5DmrSXH+APO+G8AVtOgf0JThbghFgsGKVpnHBmuJ7WzQnsDaFmlUrMtZ4RrjphNArIuVm/T0A+ys91rOeeDtdnZHQR5AEY20RqJ9i
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

