apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCBYm2AngcbgJeW4sY2GbVeNedhvvQA1DHmv6jwP2l1RgeSJLhHLquYsyWLwlSIgHTUvbhdXJbWQ3Z6B7HQ82ntRhAi2VAch23zMSrDiJM6iL4TNiTGIDUv/sx9O0BsKkCj6ldb+Q0Se5TIBGpuYGIdfvhtKPUxuc+YbvGOBrkRXfRcrWW5JOJ/4lFat77Ea+aDkEP4gZ266JTn88fuQil/Ciz7WVbKkV4NmT+ffUOwoxRNrRPKvlJxfO3+xUAx/6hHABMKIXory4e5tPPk3vaxRsKG/f5yaVXiCL/RL4fspYd6P/NWk1w1ZbcJsdwmhppf7GMpa1fMwyXEjzEg7hGxV9fVsQE/Sz5sSm6DQ0M0wEJlGdeK/V1OcF5qzG50ruhsIRiLELH9dhkhCkokjtd6L1cegUs+38AzwwVj16qc/v4elyGDio4jr5wRdyJQmo9Kq2RtVJub89mRfAOvYEYdgMHUN1LBphjC014vim+QLakyQP4jBVcKAdINCRAHyJ5d/k9MPBffB4QJGsqgFf6DctuDAtTOQ+i9aB3cL/ZkY3wAUp8vHnW+YFAfOiyaAoNWb0R0quN3cxCbx20RpSsAcUCtTUzwxL7payxjnmVYmIHoWyRAArfy42jleFcPu2wEoFvExwSD2tO3H7NV9wxSxDeXcIYgCDya6LrM/Ghe5XiyCPHVpr/IGi8wuz/scFbL5DGlJI/vjlJd+6Uj68WYJaukFRAwsmgv/m5zX2B80RVbPcT7w6Ae
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

