apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCau5gJCeCt0nplkK8IMcEviMZ84Cu6mWmgsHHt/6RumodemAlhXOT8zp4nrfbbCg/QHMVqWbAcC5LqOE+BtWcLGZmZcEHLIqSWYZjR1rM1AW/ESuIr4h8KupN21YVc9RIBi5cFM3QxvsAfax9fLQOkr9sjGhVLg6qgtovewNtCy3qm5EGg6LTDkKO3ulYzk+VkAR0cANVd2qrC65juRlL8HeXPYQ2IYvXR+C2OvuB2xeuHCc2W2rTVLpf0lizynrSqXm6JdaBIdMviIXvHNwHL2svDUKcW3vhNg/EIlX7cbE+vLYDh+ai8fgCVFPwTdxsVt9FZJKCPRpAU5869aiOqxW/farerB594kUPrIwL4Qs2boiG0BzvrlPmud9SKo5IX3qaPQEzpLnCrVZywNY+JRCBL9dDAGTUb6BuotrXhCMaCyQxm1k1R9OnGXL8KpEQA3snVGWeK0J7doFbKOuMpudztm+h/wZK9+fclRXAS+FhvTIR15o3oT8DL5csBIFN6StEaP5ctVdwZTJFCmK6/bmVjRx3Q7Ah830dAImgnJkx7EYXluvX0HuyGpwDoAjnq0nZidAwzXV3Z20sfXv3DmRd5nxfaeu2lXv0xeCINhnENnGxZ32vHQ1bqiZel4zooQEpjq2v0506SJzyNE9o9A4pyl/6jtZAnsPHgEffkzS1UGWdg1//N1BJUX2gnA5JSP7443qgDVaT5cdE1sBZZgZ7svqz+kujyL8QMYqpn4BeYo58tnEqi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

