{
 "title": "demo-3",
 "description": "HPA",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Real-time QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_http_requests{job=\"prometheus-metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(total_http_requests{job=\"prometheus-metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(response_status{job=\"prometheus-metrics\"}) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{job=\"prometheus-metrics\"}[1m])) by(le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_response_time_seconds_bucket{job=\"prometheus-metrics\"}[1m])) by(le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket{job=\"prometheus-metrics\"}[1m])) by(le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{job=\"prometheus-metrics\"}[1m])) by(le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface QPS detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(total_http_requests{job=\"prometheus-metrics\"}[1m])) by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_bucket{job=\"prometheus-metrics\"}[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}