apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-vault # ref secretStore CRD
    kind: ClusterSecretStore
  target:
    name: my-secret # secret name
  data:
    - secretKey: MY_USERNAME # K8S secret key in the secret
      remoteRef:
        key: k8s/example # vault secret path
        property: USERNAME # vault secret key
    - secretKey: MY_PASSWORD # K8S secret key in the secret
      remoteRef:
        key: k8s/example # vault secret path
        property: PASSWORD # vault secret key
