apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-demo2
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: secret-store-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: secret-demo2  # secret name to push
  data:
    - match:
        secretKey: username # key in secret to push
        remoteRef:
          remoteKey: k8s/example  # Vault path
    - match:
        secretKey: password # key in secret to push
        remoteRef:
          remoteKey: k8s/example  # Vault path
