apiVersion: v1
kind: Secret
metadata:
  name: secret-demo2
  namespace: default  # Change this if you want to use a different namespace
type: Opaque
data:
  # Replace with your key-value pairs. The values must be base64 encoded.
  username: dXNlcm5hbWU=  # base64 for 'username'
  password: cGFzc3dvcmQ=  # base64 for 'password'
