apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCmxgFru+/D1JOglkld2lEPpWLUFsRaGPN1IhazeAdJlmR/cHx5rqCTFS2s81+txf5EQ9qSbM3VwpVOZeCuae9dygiT2cHxpSiabIk2Ybs3n70b88lfYASbJWhJWT/nedH30s+g9c1/F2nDulUF544BYW+zrlZN5mmELDBkcNy2IXw7s++H4LSK4kaVBUU+d/zYAPUB9Iy/lsiiyHn1sR7alrtX10b3it1WiwOlJ0nxZYzi6lGkxK4NYSgaqyp5Ph3RLUz6JFqOqsF5DSNd1Cxy2+WleXyqR67qMkS0+SKgTyDVvdhISf8NO+DIYGQ9qZSqqEUsQPocdjeevJg0TxHux1jFQMzHAlNW9rWQfRs0WRT9Ofwjip4v1PgAwmteS/+HGEO9SL3Ps5d8++qYCAmpvdGAQ4wx7KNRht4HIx3nNcTGPEWasXi3EygZXHfDhlLA7ehoOuq90VtxNcKOISqs02kZuO6jFD0p0EZPXAXhay1xI9N5xWzTZliQ6ggtSchB2CduhEV8Yxo5HD7mBj1K4dbiiINkULQkAOxSipsFLhm98yUET95xnxmwk/Vnzdto11hnGK+aYjqSnW1aNM9Ofepu9dGN2erXYSO4I0jGlgl7Z1mInPW9AQAhXMRCJzVIHmOBgADNkQcFFEWnM4uhYnz1/plyD6OCtMh5jwBXdyn5qvkFGURMuKPWQC07Od4JawXpiyrDRYpsIudildrtq9E2h79gdFR/0PmiHOWwZzYIUhTx0h3/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

