apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCnHUSGqQrUy5ni71Rya1lmnSaaKX6lgaTlrZK14FpAN8T0KSElyjDn6NjjN8kLb6LlF6e4QQF/3wHCI0TQfbHhhFSqZSy585VD/o0WMxcXqJWge/IA/fQ/EciGrDbPKlQyufvGXAfxZm/Wt1bW2Lsk3hmPqw98cL2rUlB7+MSWEMvDg1qFcpJunjByavG1hnY1n2WkodT/Sg9lyMkUH5D2jCJBq5ReJd6K/sypiGs9RQ16r6faoSTP2ScLJJXDziTSNlU8lwTNsVvZCG79Y6D9f3T5JsvuR/Z18PcApQxkY0xo032jqZMqdK6hYxBddatnZnhu5Rut/R0pUc+gIasjKQad6Fosp0c+wBByuqybCZ9YxkkMaidQJe7bABVrD/0Sx4scc0qTLbwkNGhNC82h8V1koJpKyQtQDR7N48AMvYD5gckVTPdvIUpYQRLgZJQmmG5quCmeWLcCeM5srrpFPy1gLjj4LnLDXgnRHn/NCxcJDxFwEEjPeUqEv0qoY56kutGa6KQ9ZbFWrIpgQVWyt3YRc9+HOkSBm+ceP03y+kRLQsnextITzpCkGomqpyv/P1/I3zoSW/8aWuD1a6HHOkrYxuETX5ezANmeSRxsqw1jDFBqdLKUA8w0fRgY8dbki4T605im9Cb9FQBpL4SoqyHUhe8R/75sGz1Y/3rQNDA5ASF20nCi3IjjwICWHl72nfrRqqTj8fFCF75oGH11g1r1sI0Rtatc5ioDUlQEZ2je2fZp+o5a
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

