# http://sonarqube.${var.prefix}.${var.domain}
# https://docs.sonarsource.com/sonarqube/latest/user-guide/managing-tokens/
apiVersion: v1
kind: Secret
metadata:
  name: "sonar-token"
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description": "credentials from Kubernetes of Sonarqube"
type: Opaque
stringData:
  text: "<token>"