# http://sonarqube.${var.prefix}.${var.domain}
apiVersion: v1
kind: Secret
metadata:
  name: "sonar-token"
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description": "credentials from Kubernetes of Sonarqube"
type: Opaque
# https://docs.sonarsource.com/sonarqube/latest/user-guide/managing-tokens/
stringData:
  text: "squ_f8cc6667cb039ff06da4725fbe75cbd46e951493"